image: node:alpine
include:
  project: 'ezapi_poc/infra_poc'
  file: 
    - 'reactuicitest.yml'
    - 'reactuicistage.yaml'
    - 'reactuiciprod.yaml'
    - 'deploy-reactui-test-1.yaml'
    - 'deploy-reactui-demo-1.yaml'
    - 'deploy-reactui-instance-1.yaml'
stages:
  - build-test
  - build-stage
  - build-prod 
  - deploy-test1
  - deploy-demo1
  - deploy-instance1 
build-stage:
  stage: build-stage 
  extends: .build-stage
  only:
    - stage
build-test:
  stage: build-test 
  extends: .build-test
  only:
    - test    
build-prod:
  stage: build-prod
  extends: .build-prod
  only:
    - master    
deploy-test1:
  stage: deploy-test1
  image: alpine  
  extends: .deploy-test1
  only: 
    - test    
deploy-demo1:  
  stage: deploy-demo1
  image: alpine  
  extends: .deploy-demo1
  only:
    - master
deploy-instance1:
  stage: deploy-instance1
  image: alpine  
  extends: .deploy-instance1
  only: 
    - stage       
