import React, { useState } from "react";
import { useDrag } from "react-dnd";
import DragIndicatorIcon from "@material-ui/icons/DragIndicator";
import AccountTreeIcon from "@material-ui/icons/AccountTree";
import classNames from "classnames";
import { Drawer } from "@material-ui/core";
import _ from "lodash";
import {
  useGetRecoilValueInfo_UNSTABLE,
  useRecoilState,
  useSetRecoilState,
  useRecoilValue,
} from "recoil";
import AddIcon from "@mui/icons-material/Add";
import AppIcon from "../../../shared/components/AppIcon";
import Colors from "../../../shared/colors";
import AttributeIcon from "../../../static/images/attribute.svg";
import StoredProcedureIcon from "../../../static/images/stored-procedure.svg";
import InputIcon from "../../../static/images/input.svg";
import OutputIcon from "../../../static/images/output.svg";

import ColumnIcon from "../../../static/images/column-icon.svg";
import autoGenrateIcon from "../../../static/images/auto-generate.svg";
import {
  isArray,
  isAttribute,
  isColumn,
  isDatabase,
  isObject,
  isSchema,
  operationAtomWithMiddleware,
  useGetFullPath,
  isItemSame,
  isStoredProcedure,
  isAutoGenerated,
  useCanEdit,
} from "../../../shared/utils";

const StoredProcedureItem = ({
  index,
  section,
  item,
  primaryKey,
  onItemClick2,
}) => {
  const { fetch: fetchFullPath } = useGetFullPath();
  let [operationData, setOperationDetails] = useRecoilState(
    operationAtomWithMiddleware
  );
  // const getResponseData = (operation) => {
  //   return operation?.operationResponse?.find(
  //     (item) => item.responseCode === responseCode
  //   );
  // };

  // const getResponseIndex = (operation) => {
  //   return operation?.operationResponse?.findIndex(
  //     (item) => item.responseCode === responseCode
  //   );
  // };
  function insertStateProcedures(item) {
    setOperationDetails((operationDetails) => {
      const path = fetchFullPath(item);
      if (
        !operationDetails.operationRequest.body.find((x) =>
          isItemSame(x, item, path)
        ) &&
        isAutoGenerated(item, operationData)
      ) {
        //request

        const newOperationDetails = _.cloneDeep(operationDetails);
        const clonedItem = _.cloneDeep(item);

        clonedItem["name"] = clonedItem.storedProcedure;
        clonedItem["required"] = true;
        clonedItem["payloadId"] = "H4pIyr5l6UJ";
        delete clonedItem._id;
        delete clonedItem.storedProcedure;
        delete clonedItem.schema;
        delete clonedItem.projectid;
        delete clonedItem.outputAttributes;
        newOperationDetails.operationRequest.body.push(clonedItem);
        return newOperationDetails;
      }

      // response
      const clonedOperationDetails = _.cloneDeep(operationDetails);
      const clonedItem = _.cloneDeep(item);
      // clonedResponseData.body.push(clonedItem);

      // clonedOperationDetails.operationResponse[responseIndex] =
      //   clonedResponseData;

      return clonedOperationDetails;

      return operationDetails;
    });
  }
  return (
    <div
      // ref={canEdit() ? drag : null}
      style={{
        backgroundColor: "white",
      }}
      className='p-2 mb-2 rounded-md flex flex-row items-center'
      onClick={(e) => {
        e?.preventDefault();
        e?.stopPropagation();
        if (section == 0) {
          onItemClick2(item);
        }
      }}
    >
      <img
        className='mr-2'
        src={
          section == 0
            ? StoredProcedureIcon
            : section == 1
            ? InputIcon
            : OutputIcon
        }
        style={{ width: "24px", height: "24px" }}
      />

      <p className='flex-1 text-overline3 mr-2 overflow-ellipsis'>
        {section == 0 ? item?.storedProcedure : item?.name}
      </p>
      {section == 0 ? (
        <AppIcon
          onClick={(e) => {
            e?.preventDefault();
            e?.stopPropagation();
            insertStateProcedures(item);
          }}
          style={{ marginRight: "1rem" }}
        >
          <AddIcon htmlColor='#c72c71' />
        </AppIcon>
      ) : null}
    </div>
  );
};

export default StoredProcedureItem;
