import React, { useState } from "react";
import { useDrag } from "react-dnd";
import DragIndicatorIcon from "@material-ui/icons/DragIndicator";
import AccountTreeIcon from "@material-ui/icons/AccountTree";
import classNames from "classnames";
import { Drawer } from "@material-ui/core";
import _ from "lodash";
import {
  useGetRecoilValueInfo_UNSTABLE,
  useRecoilState,
  useSetRecoilState,
  useRecoilValue,
} from "recoil";
import AddIcon from "@mui/icons-material/Add";
import AppIcon from "../../../shared/components/AppIcon";
import Colors from "../../../shared/colors";
import AttributeIcon from "../../../static/images/attribute.svg";
import StoredProcedureIcon from "../../../static/images/stored-procedure.svg";
import InputIcon from "../../../static/images/input.svg";
import OutputIcon from "../../../static/images/output.svg";

import ColumnIcon from "../../../static/images/column-icon.svg";
import autoGenrateIcon from "../../../static/images/auto-generate.svg";
import {
  isArray,
  isAttribute,
  isColumn,
  isDatabase,
  isObject,
  isSchema,
  operationAtomWithMiddleware,
  useGetFullPath,
  isItemSame,
  isStoredProcedure,
  isAutoGenerated,
  useCanEdit,
} from "../../../shared/utils";

const StoredProcedureItem = ({
  isAddClicked,
  index,
  section,
  item,
  primaryKey,
  itemObject,
  onItemClick2,
}) => {
  const { fetch: fetchFullPath } = useGetFullPath();
  let [operationData, setOperationDetails] = useRecoilState(
    operationAtomWithMiddleware
  );

  function insertStateProcedures(item) {
    // console.log(item);
    setOperationDetails((operationDetails) => {
      const path = fetchFullPath(item);
      // console.log(operationDetails.operationRequest.body);
      const newOperationDetails = _.cloneDeep(operationDetails);
      let checkDuplicateRequest = [];
      operationDetails.operationRequest.body.map((bodyItem) => {
        // console.log(bodyItem);
        if (item["storedProcedure"] == bodyItem["name"]) {
          // console.log("inside duplicate");
          checkDuplicateRequest.push(bodyItem);
        }
      });
      // console.log(checkDuplicateRequest, isAutoGenerated(item, operationData));
      if (
        checkDuplicateRequest.length == 0 &&
        isAutoGenerated(item, operationData) &&
        item.inputAttributes
      ) {
        // console.log("inside 1");
        //request

        const clonedItem = _.cloneDeep(item);

        clonedItem["name"] = clonedItem.storedProcedure;
        clonedItem["required"] = true;
        clonedItem["payloadId"] = null;
        delete clonedItem._id;
        delete clonedItem.storedProcedure;
        delete clonedItem.schema;
        delete clonedItem.projectid;
        delete clonedItem.outputAttributes;
        newOperationDetails.operationRequest.body.push(clonedItem);
      }

      // response
      const responseData = operationData?.operationResponse[0];
      const responseIndex = 0;
      const checkDuplicateResponse = [];

      operationDetails.operationResponse[0].body.map((bodyItem) => {
        if (item["storedProcedure"] == bodyItem["name"]) {
          return bodyItem;
        }
      });

      // const existingBodyIndex = responseData?.body?.findIndex((x) =>
      //   isItemSame(x, item, path)
      // );

      if (
        checkDuplicateResponse.length == 0 &&
        responseData &&
        responseIndex >= 0 &&
        item.outputAttributes
      ) {
        // console.log("inside 2");
        // const clonedOperationDetails = _.cloneDeep(operationDetails);
        const clonedResponseData = _.cloneDeep(responseData);
        const clonedItem = _.cloneDeep(item);

        // clonedItem["outputAttributes"] = clonedItem.data[1];
        clonedItem["name"] = clonedItem.storedProcedure;
        clonedItem["required"] = true;
        clonedItem["payloadId"] = null;

        delete clonedItem._id;
        delete clonedItem.storedProcedure;
        delete clonedItem.schema;
        delete clonedItem.projectid;
        delete clonedItem.inputAttributes;

        clonedResponseData.body.push(clonedItem);

        newOperationDetails.operationResponse[responseIndex] =
          clonedResponseData;
      }

      return newOperationDetails;
    });
  }
  return (
    <div
      // ref={canEdit() ? drag : null}
      style={{
        backgroundColor: "white",
      }}
      className='p-2 mb-2 rounded-md flex flex-row items-center'
      onClick={(e) => {
        e?.preventDefault();
        e?.stopPropagation();
        if (section == 0) {
          onItemClick2(item);
        }
      }}
    >
      <img
        className='mr-2'
        src={
          section == 0
            ? StoredProcedureIcon
            : section == 1
            ? InputIcon
            : OutputIcon
        }
        style={{ width: "24px", height: "24px" }}
      />

      <p className='flex-1 text-overline3 mr-2 overflow-ellipsis'>
        {section == 0 ? item?.storedProcedure : item?.name}
      </p>
      {section == 0 ? (
        <AppIcon
          onClick={(e) => {
            isAddClicked(true, item?.storedProcedure);
            e?.preventDefault();
            e?.stopPropagation();
            insertStateProcedures(item);
          }}
          style={{ marginRight: "1rem" }}
        >
          <AddIcon htmlColor='#c72c71' />
        </AppIcon>
      ) : null}
    </div>
  );
};

export default StoredProcedureItem;
