import React, { useState, useEffect, useCallback, useRef } from "react";
import {
  useGetRecoilValueInfo_UNSTABLE,
  useRecoilState,
  useSetRecoilState,
  useRecoilValue,
} from "recoil";
import Tooltip from "@mui/material/Tooltip";
import { CircularProgress } from "@material-ui/core";
import _ from "lodash";
import debounce from "lodash.debounce";
import DeleteIcon from "@material-ui/icons/Delete";
import TreeView from "@material-ui/lab/TreeView";
import ExpandMoreIcon from "@material-ui/icons/ExpandMore";
import ChevronRightIcon from "@material-ui/icons/ChevronRight";
import TreeItem from "@material-ui/lab/TreeItem";
import Scrollbar from "react-smooth-scrollbar";
import ReactHoverObserver from "react-hover-observer";
import { useParams } from "react-router";
import MoreVertIcon from "@material-ui/icons/MoreVert";
import {
  Dialog,
  Fade,
  makeStyles,
  Menu,
  MenuItem,
} from "@material-ui/core/index";
import StoredProcedureIcon from "../../../static/images/stored-procedure.svg";
import InputIcon from "../../../static/images/input.svg";
import OutputIcon from "../../../static/images/output.svg";
import useDoubleClick from "use-double-click";
import { Checkbox } from "@material-ui/core";

import DropArea from "../DropArea";
import operationAtom from "../../operationAtom";
import {
  isAttribute,
  isArrayOrObjectAttribute,
  isSchema,
  isArray,
  useWindowSize,
  isObject,
  isDatabase,
  isColumn,
  useGetParentName,
  operationAtomWithMiddleware,
  useCanEdit,
  useGetFullPath,
  isItemSame,
  isAutoGenerated,
  isStoredProcedure,
  isInput,
  isOutput,
} from "../../../shared/utils";
import AppIcon from "../../../shared/components/AppIcon";
import AttributeIcon from "../../../static/images/attribute.svg";
import SchemaIcon from "../../../static/images/schema-icon.svg";
import ColumnIcon from "../../../static/images/column-icon.svg";
import TableIcon from "../../../static/images/table-icon.svg";
import { useGetSubSchema, useGetTableData } from "./requestBodyQueries";
import DragAndDropMessage from "../../../shared/components/DragAndDropMessage";
import ChangeTableName from "./ChangeTableName";
import ChangeColumnName from "../ChangeColumnName";
import { useExpandedIds } from "./utils";
import Colors from "../../../shared/colors";
import primaryAtom from "../../../shared/atom/primaryAtom";
import tablesDataAtom from "../../../shared/atom/tablesDataAtom";
import { SignalCellularNullSharp } from "@mui/icons-material";

const Body = ({ request = true, responseCode, projectType = "schema" }) => {
  let [operationData, setOperationDetails] = useRecoilState(
    operationAtomWithMiddleware
  );
  // operationData;

  const { height, width } = useWindowSize();
  const { getExandedIds, setExpandedIds } = useExpandedIds([]);
  const [primaryKeyRef, setPrimaryKeyRef] = useRecoilState(primaryAtom);
  const tablesData = useRecoilValue(tablesDataAtom);
  const { fetch: fetchParentName } = useGetParentName();
  const { fetch: fetchFullPath } = useGetFullPath();

  const itemDropped = (item) => {
    let final_arr = [];
    if (isColumn(item)) {
      if (item?.foreign) {
        final_arr.push(item?.foreign?.table);
        let condition = tablesData
          .filter((table) => {
            return table.name === item.foreign.table;
          })[0]
          .selectedColumns.filter((column) => {
            return column.name === item.foreign.column;
          })[0];

        while (condition?.foreign) {
          final_arr.push(condition.foreign.table);
          condition = tablesData
            .filter((table) => {
              return table.name === condition.foreign.table;
            })[0]
            .selectedColumns.filter((column) => {
              return column.name === condition.foreign.column;
            })[0];
        }
      } else {
        final_arr = [];
      }
      setPrimaryKeyRef(final_arr);
    }
    if (
      isSchema(item) ||
      isDatabase(item) ||
      isAttribute(item) ||
      isColumn(item) ||
      isArrayOrObjectAttribute(item) ||
      isStoredProcedure(item) ||
      isInput(item) ||
      isOutput(item)
    ) {
      setOperationDetails((operationDetails) => {
        const path = fetchFullPath(item);

        if (request) {
          if (
            !operationDetails.operationRequest.body.find((x) =>
              isItemSame(x, item, path)
            ) &&
            isAutoGenerated(item, operationData)
          ) {
            const newOperationDetails = _.cloneDeep(operationDetails);
            const clonedItem = _.cloneDeep(item);
            if (isArrayOrObjectAttribute(item)) {
              clonedItem.required = true;
              clonedItem.schemaName = fetchParentName(clonedItem) ?? "global";
              clonedItem.parentName = path ?? "/";
            }
            if (isAttribute(item)) {
              clonedItem.required = true;
              clonedItem.schemaName = fetchParentName(clonedItem) ?? "global";
              clonedItem.parentName = path ?? "/";
            } else if (isColumn(item)) {
              clonedItem.tableName = fetchParentName(clonedItem) ?? "global";
            }
            if (isStoredProcedure(item)) {
              if (item["draggedFrom"] == "input") {
                clonedItem["inputAttributes"] = clonedItem.data[0];
                clonedItem["required"] = true;
                clonedItem["payloadId"] = null;
                delete clonedItem.draggedFrom;
                delete clonedItem.data;
                delete clonedItem.contentType;
              } else {
                return newOperationDetails;
              }
            }

            newOperationDetails.operationRequest.body.push(clonedItem);

            return newOperationDetails;
          }
        } else {
          const responseData = getResponseData(operationDetails);
          const responseIndex = getResponseIndex(operationDetails);

          const existingBodyIndex = responseData?.body?.findIndex((x) =>
            isItemSame(x, item, path)
          );

          if (existingBodyIndex === -1 && responseData && responseIndex >= 0) {
            const clonedOperationDetails = _.cloneDeep(operationDetails);
            const clonedResponseData = _.cloneDeep(responseData);
            const clonedItem = _.cloneDeep(item);
            if (isArrayOrObjectAttribute(item)) {
              clonedItem.required = true;
              clonedItem.schemaName = fetchParentName(clonedItem) ?? "global";
              clonedItem.parentName = path ?? "/";
            }
            if (isAttribute(item)) {
              clonedItem.required = true;
              clonedItem.schemaName = fetchParentName(clonedItem) ?? "global";
              clonedItem.parentName = path ?? "/";
            } else if (isColumn(item)) {
              clonedItem.tableName = fetchParentName(clonedItem) ?? "global";
            }

            if (isStoredProcedure(item)) {
              if (item["draggedFrom"] == "output") {
                clonedItem["outputAttributes"] = clonedItem.data[1];
                clonedItem["required"] = true;
                clonedItem["payloadId"] = null;
                delete clonedItem.draggedFrom;
                delete clonedItem.data;
                delete clonedItem.contentType;
              } else {
                return clonedOperationDetails;
              }
            }

            clonedResponseData.body.push(clonedItem);

            clonedOperationDetails.operationResponse[responseIndex] =
              clonedResponseData;

            return clonedOperationDetails;
          }
        }

        return operationDetails;
      });
    }
  };

  const getResponseData = (operation) => {
    return operation?.operationResponse?.find(
      (item) => item.responseCode === responseCode
    );
  };

  const getResponseIndex = (operation) => {
    return operation?.operationResponse?.findIndex(
      (item) => item.responseCode === responseCode
    );
  };

  return (
    <DropArea onItemDropped={itemDropped}>
      <div className=' h-full flex flex-col'>
        <div className=' ml-3 p-2 border-t-2 border-b-2 bg-neutral-gray8 mb-1/2'>
          <div className=' w-full grid grid-cols-5 gap-2 '>
            {" "}
            {/* <p className='text-overline2 text-neutral-gray4 uppercase font-bold'>
              {projectType === "schema" || projectType === "both"
                ? "Schema/Attribute"
                : projectType === "db"
                ? "Table/Column"
                : "-"}
            </p> */}
            {projectType === "db" && (
              <div className='flex justify-self-start '>
                {" "}
                <p className='text-overline2 uppercase text-neutral-gray4 font-bold'>
                  Table/Column
                </p>
              </div>
            )}
            <div className='flex justify-self-start '>
              <p className='text-overline2 uppercase text-neutral-gray4 font-bold'>
                Schema/Attribute
              </p>
            </div>
            <div className='flex justify-self-start '>
              <p className='text-overline2 uppercase text-neutral-gray4 font-bold'>
                Data Type
              </p>
            </div>
            <div className='flex justify-self-start '>
              {" "}
              <p className='text-overline2 uppercase text-neutral-gray4 font-bold'>
                is Array
              </p>
            </div>
            <div className='flex justify-self-start '>
              <p className='text-overline2 uppercase text-neutral-gray4 font-bold'>
                Required
              </p>
            </div>
          </div>
        </div>

        {request && !_.isEmpty(operationData?.operationRequest?.body) && (
          <div className='h-full flex-1'>
            <Scrollbar
              alwaysShowTracks={true}
              style={{
                maxHeight:
                  height > 790
                    ? "26vh"
                    : height > 770
                    ? "22vh"
                    : height > 600
                    ? "18vh"
                    : "13vh",
              }}
            >
              <TreeView
                defaultCollapseIcon={<ExpandMoreIcon />}
                defaultExpandIcon={<ChevronRightIcon />}
                expanded={getExandedIds() ?? []}
                onNodeToggle={(event, nodeIds) => {
                  setExpandedIds(nodeIds);
                }}
              >
                {operationData?.operationRequest?.body.map((item) => {
                  let clonedRef;

                  if (isSchema(item)) {
                    clonedRef = _.cloneDeep(item);

                    if (!clonedRef.hasOwnProperty("data")) {
                      clonedRef["data"] = [];
                    }
                  } else if (isDatabase(item)) {
                    clonedRef = _.cloneDeep(item);

                    if (!clonedRef.hasOwnProperty("selectedColumns")) {
                      clonedRef["selectedColumns"] = [];
                    }
                  } else if (isStoredProcedure(item)) {
                    clonedRef = _.cloneDeep(item);
                  } else if (isArray(item) || isObject(item)) {
                    clonedRef = _.cloneDeep(item);
                  }

                  return clonedRef == "wrongData" ? null : (
                    <BodyItem
                      projectType={projectType}
                      key={item?.name}
                      itemRef={clonedRef ?? item}
                      request={request}
                      responseCode={responseCode}
                    />
                  );
                })}
              </TreeView>
            </Scrollbar>
          </div>
        )}

        {!request && !_.isEmpty(getResponseData(operationData)?.body) && (
          <div className='h-full flex-1'>
            <Scrollbar
              alwaysShowTracks={true}
              style={{
                maxHeight:
                  height > 790
                    ? "23vh"
                    : height > 770
                    ? "19vh"
                    : height > 600
                    ? "15vh"
                    : "10vh",
              }}
            >
              <TreeView
                defaultCollapseIcon={<ExpandMoreIcon />}
                defaultExpandIcon={<ChevronRightIcon />}
                expanded={getExandedIds() ?? []}
                onNodeToggle={(event, nodeIds) => {
                  setExpandedIds(nodeIds);
                }}
              >
                {getResponseData(operationData)?.body.map((item) => {
                  let clonedRef;

                  if (isSchema(item)) {
                    clonedRef = _.cloneDeep(item);

                    if (!clonedRef.hasOwnProperty("data")) {
                      clonedRef["data"] = [];
                    }
                  } else if (isDatabase(item)) {
                    clonedRef = _.cloneDeep(item);

                    if (!clonedRef.hasOwnProperty("selectedColumns")) {
                      clonedRef["selectedColumns"] = [];
                    }
                  } else if (isStoredProcedure(item)) {
                    clonedRef = _.cloneDeep(item);
                  } else {
                  }

                  return clonedRef == "wrongData" ? null : (
                    <BodyItem
                      projectType={projectType}
                      key={item.name}
                      itemRef={clonedRef ?? item}
                      request={request}
                      responseCode={responseCode}
                    />
                  );
                })}
              </TreeView>
            </Scrollbar>
          </div>
        )}

        {request && _.isEmpty(operationData?.operationRequest?.body) && (
          <div className='border-dashed p-3 bg-neutral-gray7 rounded-md border-2 m-2 flex flex-row justify-center'>
            <DragAndDropMessage isSchemaAllowed isAttributeAllowed />
          </div>
        )}

        {!request && _.isEmpty(getResponseData(operationData)?.body) && (
          <div className='border-dashed p-3 bg-neutral-gray7 rounded-md border-2 m-2 flex flex-row justify-center'>
            <DragAndDropMessage isTableAllowed isColumnAllowed />
          </div>
        )}
      </div>
    </DropArea>
  );
};

let treeIndex = 1;
const truncateLength = 20; //max character length limit of names to enable truncate
// This can either be a schema or table or stored procedure
const BodyItem = ({ request = true, responseCode, itemRef, projectType }) => {
  const [bodyItem, setItem] = useState(itemRef);
  const setOperationDetails = useSetRecoilState(operationAtomWithMiddleware);
  const { projectId } = useParams();
  const {
    isLoading: isLoadingSubSchema,
    error: getSubSchemasError,
    data: subSchemaData,
    mutate: getSubSchema,
    reset: resetSubSchemaData,
    variables: subSchemaRequest,
  } = useGetSubSchema();
  const {
    isLoading: isLoadingTableData,
    data: tableData,
    mutate: getTable,
  } = useGetTableData();
  const canEdit = useCanEdit();
  const getRecoilValueInfo = useGetRecoilValueInfo_UNSTABLE();

  useEffect(() => {
    if (subSchemaData) {
      let itemsToConsider = [];

      if (
        subSchemaData?.nSchemaArray &&
        !_.isEmpty(subSchemaData?.nSchemaArray)
      ) {
        itemsToConsider = subSchemaData?.nSchemaArray[0].data;
      } else if (subSchemaData?.data && !_.isEmpty(subSchemaData?.data)) {
        itemsToConsider = subSchemaData?.data;
      }

      if (isSchema(bodyItem) || isArray(bodyItem) || isObject(bodyItem)) {
        for (let index = 0; index < itemsToConsider.length; index++) {
          const element = itemsToConsider[index];
          bodyItem.data.push(element);
        }
        const clonedClonedRef = _.cloneDeep(bodyItem);

        setItem(clonedClonedRef);
      }
    }
  }, [subSchemaData]);

  useEffect(() => {
    if (tableData) {
      setItem(tableData);
    }
  }, [tableData]);

  useEffect(() => {
    setItem(itemRef);
  }, [itemRef]);

  const deleteItem = (item) => {
    if (
      isSchema(item) ||
      isColumn(item) ||
      isAttribute(item) ||
      isDatabase(item) ||
      isStoredProcedure(item) ||
      (isArrayOrObjectAttribute(item) && canEdit())
    ) {
      setOperationDetails((operationDetails) => {
        if (request) {
          const index = operationDetails.operationRequest.body.findIndex(
            (x) => x?.name === item?.name
          );
          if (index !== -1) {
            const newOperationDetails = _.cloneDeep(operationDetails);

            newOperationDetails.operationRequest.body.splice(index, 1);

            return newOperationDetails;
          }
        } else {
          const responseData = operationDetails?.operationResponse?.find(
            (item) => item.responseCode === responseCode
          );
          const responseIndex = operationDetails?.operationResponse?.findIndex(
            (item) => item.responseCode === responseCode
          );

          const existingBodyIndex = responseData?.body?.findIndex(
            // (body) => body?.sourceName === item?.sourceName
            (body) => body?.name === item?.name
          );

          if (existingBodyIndex >= 0 && responseData && responseIndex >= 0) {
            const clonedOperationDetails = _.cloneDeep(operationDetails);
            const clonedResponseData = _.cloneDeep(responseData);

            clonedResponseData.body.splice(existingBodyIndex, 1);

            clonedOperationDetails.operationResponse[responseIndex] =
              clonedResponseData;

            return clonedOperationDetails;
          }
        }

        return operationDetails;
      });
    }
  };
  const isArrayChecked = (item, isArrayValue, reqType) => {
    setOperationDetails((operationDetails) => {
      if (request) {
        var requestData = null;
        var requestIndex = null;
        operationDetails?.operationRequest?.body.map((row, index) => {
          if (row.payloadId === item.payloadId) {
            requestData = row;
            requestIndex = index;
          }
        });

        if (requestData && requestIndex >= 0) {
          const clonedOperationDetails = _.cloneDeep(operationDetails);
          const clonedRequestData = _.cloneDeep(requestData);

          clonedRequestData.isArray = isArrayValue;
          clonedOperationDetails.operationRequest.body[requestIndex] =
            clonedRequestData;

          return clonedOperationDetails;
        }
      } else {
        const responseData = operationDetails?.operationResponse?.find(
          (item) => item.responseCode === responseCode
        );
        const responseIndex = operationDetails?.operationResponse?.findIndex(
          (item) => item.responseCode === responseCode
        );

        // const existingBodyIndex = responseData?.body?.findIndex(
        //   // (body) => body?.sourceName === item?.sourceName
        //   (body) => body?.name === item?.name
        // );
        const tableIndex = responseData?.body?.findIndex(
          (body) => body?.sourceName === item?.sourceName
        );
        if (tableIndex >= 0 && responseData && responseIndex >= 0) {
          const clonedOperationDetails = _.cloneDeep(operationDetails);
          const clonedResponseData = _.cloneDeep(responseData);
          //  const clonedTable = _.cloneDeep(clonedResponseData.body[tableIndex]);
          clonedResponseData.body[tableIndex].isArray = isArrayValue;

          clonedOperationDetails.operationResponse[responseIndex] =
            clonedResponseData;

          return clonedOperationDetails;
        }
      }

      return operationDetails;
    });
  };

  const deleteColumnOfTable = (column, table) => {
    if (isColumn(column) && isDatabase(table) && canEdit()) {
      setOperationDetails((operationDetails) => {
        if (request) {
          const newOperationDetails = _.cloneDeep(operationDetails);

          const tableIndex =
            newOperationDetails.operationRequest.body.findIndex(
              (x) => isDatabase(x) && x?.sourceName === table?.sourceName
            );

          if (tableIndex !== -1) {
            const clonedTable = _.cloneDeep(
              newOperationDetails.operationRequest.body[tableIndex]
            );

            const columnIndex =
              clonedTable?.selectedColumns?.findIndex(
                (x) => isColumn(x) && x?.sourceName === column?.sourceName
              ) ?? -1;

            if (columnIndex !== -1) {
              clonedTable.selectedColumns.splice(columnIndex, 1);
            }

            newOperationDetails.operationRequest.body[tableIndex] = clonedTable;

            return newOperationDetails;
          }
        } else {
          const responseData = operationDetails?.operationResponse?.find(
            (item) => item.responseCode === responseCode
          );
          const responseIndex = operationDetails?.operationResponse?.findIndex(
            (item) => item.responseCode === responseCode
          );

          const tableIndex = responseData?.body?.findIndex(
            (body) => body?.sourceName === table?.sourceName
          );

          if (tableIndex >= 0 && responseData && responseIndex >= 0) {
            const clonedOperationDetails = _.cloneDeep(operationDetails);
            const clonedResponseData = _.cloneDeep(responseData);
            const clonedTable = _.cloneDeep(
              clonedResponseData.body[tableIndex]
            );

            const columnIndex =
              clonedTable?.selectedColumns?.findIndex(
                (x) => isColumn(x) && x?.sourceName === column?.sourceName
              ) ?? -1;

            if (columnIndex !== -1) {
              clonedTable.selectedColumns.splice(columnIndex, 1);
            }

            clonedResponseData.body[tableIndex] = clonedTable;

            clonedOperationDetails.operationResponse[responseIndex] =
              clonedResponseData;

            return clonedOperationDetails;
          }
        }

        return operationDetails;
      });
    }
  };

  const renameColumn = (column, name) => {
    if (canEdit()) {
      setOperationDetails((operationDetails) => {
        if (request) {
          const newOperationDetails = _.cloneDeep(operationDetails);

          // Get column index
          const columnIndex =
            newOperationDetails.operationRequest.body.findIndex(
              (bodyItem) => column?.sourceName === bodyItem?.sourceName
            );

          if (columnIndex !== -1) {
            // Clone column
            const clonedColumn = _.cloneDeep(
              newOperationDetails.operationRequest.body[columnIndex]
            );

            // Set updated name to column
            clonedColumn.name = name;

            // Set cloned column to body
            newOperationDetails.operationRequest.body[columnIndex] =
              clonedColumn;

            return newOperationDetails;
          }
        } else {
          const responseIndex = operationDetails?.operationResponse?.findIndex(
            (item) => item.responseCode === responseCode
          );

          if (responseIndex !== -1) {
            const clonedOperationDetails = _.cloneDeep(operationDetails);
            const clonedResponseData = _.cloneDeep(
              operationDetails?.operationResponse[responseIndex]
            );

            // Get column
            const columnIndex = clonedResponseData?.body?.findIndex(
              (bodyItem) => column?.sourceName === bodyItem?.sourceName
            );

            if (columnIndex !== -1) {
              // Clone column
              const clonedColumn = _.cloneDeep(
                clonedResponseData?.body[columnIndex]
              );

              // Set updated name to column
              clonedColumn.name = name;

              // Set cloned column to body
              clonedResponseData.body[columnIndex] = clonedColumn;
            }

            clonedOperationDetails.operationResponse[responseIndex] =
              clonedResponseData;

            return clonedOperationDetails;
          }
        }

        return operationDetails;
      });
    }
  };

  const isNameTaken = (item, name) => {
    if (canEdit()) {
      const { loadable: operationAtom } = getRecoilValueInfo(
        operationAtomWithMiddleware
      );
      const operationDetails = operationAtom?.contents;

      if (request) {
        const newOperationDetails = _.cloneDeep(operationDetails);

        // Get column index
        const columnIndex = newOperationDetails.operationRequest.body.findIndex(
          (bodyItem) =>
            bodyItem?.name === name && bodyItem?.sourceName !== item?.sourceName
        );

        if (columnIndex !== -1) {
          return true;
        }
      } else {
        const responseIndex = operationDetails?.operationResponse?.findIndex(
          (item) => item.responseCode === responseCode
        );

        if (responseIndex !== -1) {
          // Get column
          const columnIndex = operationDetails?.operationResponse[
            responseIndex
          ]?.body?.findIndex(
            (bodyItem) =>
              bodyItem?.name === name &&
              bodyItem?.sourceName !== item?.sourceName
          );

          if (columnIndex !== -1) {
            return true;
          }
        }
      }

      return false;
    }

    return false;
  };

  const renameColumnOfTable = (column, table, name) => {
    if (canEdit()) {
      setOperationDetails((operationDetails) => {
        if (request) {
          const newOperationDetails = _.cloneDeep(operationDetails);

          // Get parent table index
          const parentTableIndex =
            newOperationDetails.operationRequest.body.findIndex(
              (bodyItem) =>
                isDatabase(bodyItem) &&
                table?.sourceName === bodyItem?.sourceName
            );

          if (parentTableIndex !== -1) {
            // Clone parent table
            const clonedParentTable = _.cloneDeep(
              newOperationDetails.operationRequest.body[parentTableIndex]
            );

            // Get column
            const columnIndex = clonedParentTable?.selectedColumns?.findIndex(
              (columnItem) => column?.sourceName === columnItem?.sourceName
            );

            if (columnIndex !== -1) {
              // Clone column
              const clonedColumn = _.cloneDeep(
                clonedParentTable.selectedColumns[columnIndex]
              );

              // Set updated name to column
              clonedColumn.name = name;

              // Set cloned column to table
              clonedParentTable.selectedColumns[columnIndex] = clonedColumn;

              // Set table to operations body
              newOperationDetails.operationRequest.body[parentTableIndex] =
                clonedParentTable;
            }

            return newOperationDetails;
          }
        } else {
          const responseIndex = operationDetails?.operationResponse?.findIndex(
            (item) => item.responseCode === responseCode
          );
          if (responseIndex !== -1) {
            const responseData =
              operationDetails?.operationResponse[responseIndex];
            const clonedOperationDetails = _.cloneDeep(operationDetails);
            const clonedResponseData = _.cloneDeep(responseData);

            const tableIndex = responseData?.body?.findIndex(
              (body) => body?.sourceName === table?.sourceName
            );

            if (tableIndex !== -1) {
              const clonedTableData = _.cloneDeep(
                clonedResponseData.body[tableIndex]
              );

              // Get column
              const columnIndex = clonedTableData?.selectedColumns?.findIndex(
                (columnItem) => column?.sourceName === columnItem?.sourceName
              );

              if (columnIndex !== -1) {
                // Clone column
                const clonedColumn = _.cloneDeep(
                  clonedTableData.selectedColumns[columnIndex]
                );

                // Set updated name to column
                clonedColumn.name = name;

                // Set cloned column to table
                clonedTableData.selectedColumns[columnIndex] = clonedColumn;

                // Set table to response data body
                clonedResponseData.body[tableIndex] = clonedTableData;
              }

              clonedOperationDetails.operationResponse[responseIndex] =
                clonedResponseData;
              return clonedOperationDetails;
            }
          }
        }

        return operationDetails;
      });
    }
  };

  const isColumnNameTakenOfTable = (column, table, name) => {
    if (canEdit()) {
      const { loadable: operationAtom } = getRecoilValueInfo(
        operationAtomWithMiddleware
      );
      const operationDetails = operationAtom?.contents;

      if (request) {
        const newOperationDetails = _.cloneDeep(operationDetails);

        // Get parent table index
        const parentTableIndex =
          newOperationDetails.operationRequest.body.findIndex(
            (bodyItem) =>
              isDatabase(bodyItem) && table?.sourceName === bodyItem?.sourceName
          );

        if (parentTableIndex !== -1) {
          // Get column
          const columnIndex = newOperationDetails.operationRequest.body[
            parentTableIndex
          ]?.selectedColumns?.findIndex((columnItem) => {
            return (
              columnItem?.name === name &&
              columnItem?.sourceName !== column?.sourceName
            );
          });

          if (columnIndex !== -1) {
            return true;
          }
        }
      } else {
        const responseIndex = operationDetails?.operationResponse?.findIndex(
          (item) => item.responseCode === responseCode
        );

        if (responseIndex !== -1) {
          const responseData =
            operationDetails?.operationResponse[responseIndex];

          const tableIndex = responseData?.body?.findIndex(
            (body) => body?.sourceName === table?.sourceName
          );

          if (tableIndex !== -1) {
            // Get column
            const columnIndex = responseData.body[
              tableIndex
            ]?.selectedColumns?.findIndex(
              (columnItem) =>
                columnItem?.name === name &&
                columnItem?.sourceName !== column?.sourceName
            );

            if (columnIndex !== -1) {
              return true;
            }
          }
        }
      }
    }

    return false;
  };

  const getSchemaData = (schemaRef) => {
    if (!isLoadingSubSchema && _.isEmpty(schemaRef.data)) {
      getSubSchema({
        projectId,
        name: schemaRef?.name,
        type: schemaRef?.type,
        ref: schemaRef?.ref,
      });
    }
  };

  const getTableData = (tableRef) => {
    if (!isLoadingTableData && _.isEmpty(tableRef.selectedColumns)) {
      getTable({
        projectId,
        ref: tableRef?.name,
      });
    }
  };

  const onItemClick = () => {
    if (isDatabase(bodyItem)) {
      if (!bodyItem?.selectedColumns || _.isEmpty(bodyItem?.selectedColumns)) {
        getTableData(bodyItem);
      }
    } else if (isSchema(bodyItem)) {
      getSchemaData(bodyItem);
    }
  };

  if (isAttribute(bodyItem) || isArray(bodyItem) || isObject(bodyItem)) {
    return (
      <AttributeLabel
        labelItem={bodyItem}
        deleteItem={deleteItem}
        request={request}
        responseCode={responseCode}
        projectType={projectType}
      />
    );
  }

  if (isColumn(bodyItem)) {
    return (
      <ColumnLabel
        columnLabelItem={bodyItem}
        deleteColumn={deleteItem}
        renameColumn={renameColumn}
        isNameTaken={isNameTaken}
        request={request}
        responseCode={responseCode}
      />
    );
  }

  return (
    <TreeItem
      key={bodyItem?.payloadId ?? bodyItem?.name ?? treeIndex++}
      nodeId={bodyItem?.payloadId ?? bodyItem?.name ?? treeIndex++}
      label={
        isDatabase(bodyItem) ? (
          <DatabaseLabel
            tableLabelItem={bodyItem}
            deleteItem={deleteItem}
            isArrayChecked={isArrayChecked}
            request={request}
            responseCode={responseCode}
          />
        ) : bodyItem != "wrongData" && isStoredProcedure(bodyItem) ? (
          <StoredProcedureLabel
            storedProcedureLabelItem={bodyItem}
            deleteItem={deleteItem}
            isArrayChecked={isArrayChecked}
            request={request}
            responseCode={responseCode}
          />
        ) : isSchema(bodyItem) ? (
          <SchemaLabel
            labelItem={bodyItem}
            deleteItem={deleteItem}
            isArrayChecked={isArrayChecked}
            isLoading={isLoadingSubSchema}
            request={request}
            responseCode={responseCode}
          />
        ) : null
      }
      onLabelClick={(e) => {
        e.preventDefault();
        e.stopPropagation();

        onItemClick();
      }}
      onIconClick={(e) => {
        onItemClick();
      }}
    >
      {isSchema(bodyItem) &&
        bodyItem?.data?.map((ref) => {
          // Sub schema/array/object
          if (isSchema(ref) || isArray(ref) || isObject(ref)) {
            const clonedRef = _.cloneDeep(ref);

            if (!clonedRef.hasOwnProperty("data")) {
              clonedRef["data"] = [];
            }

            if (!clonedRef.hasOwnProperty("isLoaded")) {
              clonedRef["isLoaded"] = false;
            }

            return <BodySubTreeItems currentRef={clonedRef} />;
          }
          //attributes within a schema
          else if (isAttribute(ref)) {
            return (
              <TreeItem
                key={ref?.payloadId ?? ref?.name ?? treeIndex++}
                nodeId={ref?.payloadId ?? ref?.name ?? treeIndex++}
                label={
                  <div className='flex flex-row p-1 justify-between items-center border-b-2 h-8'>
                    <div className='flex flex-row items-center justify-start w-full'>
                      <div className='w-full grid grid-cols-5 gap-2 items-center '>
                        <div className='flex justify-self-start items-center'>
                          {" "}
                          <img
                            src={AttributeIcon}
                            alt='conektto logo'
                            className='bg-white mr-2'
                            style={{
                              height: "24px",
                              width: "24px",
                            }}
                          />
                          <p className='text-overline2'>{ref?.name}</p>
                        </div>

                        <div className='flex-1'>
                          <p>{ref?.type}</p>
                        </div>
                        <div> {/* empty isarray */}</div>
                        <div className='flex-1'>{/* empty isRequired */}</div>
                      </div>
                    </div>
                  </div>
                }
              />
            );
          }
        })}

      {isDatabase(bodyItem) &&
        bodyItem?.selectedColumns?.map((ref) => {
          return (
            <ColumnLabel
              columnLabelItem={ref}
              deleteColumn={(column) => deleteColumnOfTable(column, bodyItem)}
              renameColumn={(column, name) =>
                renameColumnOfTable(column, bodyItem, name)
              }
              request={request}
              isNameTaken={(column, value) => {
                return isColumnNameTakenOfTable(column, bodyItem, value);
              }}
              responseCode={responseCode}
            />
          );
        })}

      {bodyItem.inputAttributes &&
        isStoredProcedure(bodyItem) &&
        bodyItem?.inputAttributes?.map((ref) => {
          return (
            <InputOrOutputLabel
              inputOrOutputLabelItem={ref}
              // deleteColumn={(column) => deleteColumnOfTable(column, bodyItem)}
              renameColumn={(column, name) =>
                renameColumnOfTable(column, bodyItem, name)
              }
              request={request}
              isNameTaken={(column, value) => {
                return isColumnNameTakenOfTable(column, bodyItem, value);
              }}
              responseCode={responseCode}
            />
          );
        })}
      {bodyItem.outputAttributes &&
        isStoredProcedure(bodyItem) &&
        bodyItem?.outputAttributes?.map((ref) => {
          return (
            <InputOrOutputLabel
              inputOrOutputLabelItem={ref}
              // deleteColumn={(column) => deleteColumnOfTable(column, bodyItem)}
              renameColumn={(column, name) =>
                renameColumnOfTable(column, bodyItem, name)
              }
              request={request}
              isNameTaken={(column, value) => {
                return isColumnNameTakenOfTable(column, bodyItem, value);
              }}
              responseCode={responseCode}
            />
          );
        })}
    </TreeItem>
  );
};

// This is shown only for arrays, schemas, objects of a parent schema
const BodySubTreeItems = ({ currentRef: some }) => {
  const [currentRef, setCurrentRef] = useState(some);
  const { projectId } = useParams();
  const {
    isLoading: isLoadingSubSchema,
    error: getSubSchemasError,
    data: subSchemaData,
    mutate: getSubSchema,
    reset: resetSubSchemaData,
    variables: subSchemaRequest,
  } = useGetSubSchema();
  const canEdit = useCanEdit();

  useEffect(() => {
    if (subSchemaData) {
      let itemsToConsider = [];

      if (
        subSchemaData?.nSchemaArray &&
        !_.isEmpty(subSchemaData?.nSchemaArray)
      ) {
        itemsToConsider = subSchemaData?.nSchemaArray;
      } else if (subSchemaData?.data && !_.isEmpty(subSchemaData?.data)) {
        itemsToConsider = subSchemaData?.data;
      }

      if (isSchema(currentRef) || isArray(currentRef) || isObject(currentRef)) {
        currentRef.isLoaded = true;

        for (let index = 0; index < itemsToConsider.length; index++) {
          const element = itemsToConsider[index];
          currentRef.data.push(element);
        }
        const clonedClonedRef = _.cloneDeep(currentRef);

        setCurrentRef(clonedClonedRef);
      }
    }
  }, [subSchemaData]);

  const getSubschemaData = (subSchemaRef) => {
    if (
      !isLoadingSubSchema &&
      !subSchemaRef.isLoaded &&
      _.isEmpty(subSchemaRef.data) &&
      !subSchemaRef?.is_child
    ) {
      getSubSchema({
        projectId,
        name: subSchemaRef?.name,
        type: subSchemaRef?.type,
        ref: subSchemaRef?.ref,
      });
    }
  };

  return (
    <TreeItem
      key={currentRef?.payloadId ?? currentRef?.name ?? treeIndex++}
      nodeId={currentRef?.payloadId ?? currentRef?.name ?? treeIndex++}
      label={
        <div className='flex flex-row p-1 justify-between border-b-2'>
          <div className='flex flex-row items-center justify-center '>
            <img
              src={SchemaIcon}
              alt='conektto logo'
              className='bg-white mr-2'
              style={{
                height: "24px",
                width: "24px",
              }}
            />

            <div className='flex flex-row justify-between w-full items-center'>
              <p className='text-overline2 mr-4'>
                {currentRef?.name}
                {isArray(currentRef) && " [ ]"}
              </p>

              {isLoadingSubSchema && subSchemaRequest.ref === currentRef?.ref && (
                <CircularProgress
                  style={{
                    width: "1.25rem",
                    height: "1.25rem",
                  }}
                />
              )}
            </div>
          </div>
        </div>
      }
      onLabelClick={(e) => {
        e.preventDefault();
        e.stopPropagation();

        getSubschemaData(currentRef);
      }}
      onIconClick={(e) => {
        getSubschemaData(currentRef);
      }}
    >
      {currentRef.data.map((ref) => {
        if (isSchema(ref) || isArray(ref) || isObject(ref)) {
          const clonedRef = _.cloneDeep(ref);

          if (!clonedRef.hasOwnProperty("data")) {
            clonedRef["data"] = [];
          }

          if (!clonedRef.hasOwnProperty("isLoaded")) {
            clonedRef["isLoaded"] = false;
          }
          return <BodySubTreeItems currentRef={clonedRef} />;
        } else if (isAttribute(ref)) {
          return (
            <TreeItem
              key={ref?.payloadId ?? ref?.name ?? treeIndex++}
              nodeId={ref?.payloadId ?? ref?.name ?? treeIndex++}
              label={
                <div className='flex flex-row justify-between items-center p-1 border-b-2'>
                  <div className='flex flex-row items-center justify-start flex-1'>
                    <img
                      src={AttributeIcon}
                      alt='conektto logo'
                      className='bg-white mr-2'
                      style={{
                        height: "24px",
                        width: "24px",
                      }}
                    />

                    <p className='text-overline2 '>{ref?.name} </p>
                  </div>

                  <div className='flex-1'>
                    <p>{ref?.type}</p>
                  </div>

                  <div className='flex-1'>
                    {/* <Checkbox
                      checked={ref?.required}
                      // checked={true}
                      style={{
                        color: Colors.brand.secondary,
                        padding: "0",
                      }}
                    /> */}
                    {/* isRequired checkbox not needed */}
                  </div>
                </div>
              }
            />
          );
        }
      })}
    </TreeItem>
  );
};

const SchemaLabel = ({
  labelItem,
  request,
  isLoading,
  deleteItem,
  isArrayChecked,
}) => {
  const canEdit = useCanEdit();
  const [isArray, setIsArray] = useState(labelItem.isArray);

  return (
    <ReactHoverObserver>
      {({ isHovering }) => {
        return (
          <div className='flex flex-row p-1 justify-between items-center border-b-2 h-8'>
            <div className='flex flex-row items-center justify-start w-full'>
              <div className='w-full grid grid-cols-5 gap-2 items-center'>
                <div className='flex justify-self-start items-center'>
                  {" "}
                  <img
                    src={SchemaIcon}
                    alt='conektto logo'
                    className='bg-white mr-4'
                    style={{ height: "24px", width: "24px" }}
                  />
                  <p className='text-overline2'>{labelItem?.name}</p>
                </div>

                <div> {/* empty datattype */}</div>
                <div className='flex  ml-1 justify-self-start'>
                  {/* empty isArray */}
                  {/* <Checkbox
                    checked={isArray}
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();

                      isArrayChecked(labelItem, !isArray, request);
                      setIsArray(!isArray);
                    }}
                    style={{
                      color: Colors.brand.secondary,
                      padding: "0",
                    }}
                  /> */}
                </div>
                <div> {/* empty required */}</div>
                {/* {isLoading && (
                  <CircularProgress
                    style={{
                      marginLeft: "0.5rem",
                      width: "20px",
                      height: "20px",
                    }}
                  />
                )} */}
              </div>
            </div>
            <div className='w-6'>
              {" "}
              {isHovering && canEdit() && (
                <AppIcon
                  onClick={(ev) => {
                    ev?.preventDefault();
                    ev?.stopPropagation();

                    deleteItem(labelItem);
                  }}
                >
                  <DeleteIcon />
                </AppIcon>
              )}
            </div>
          </div>
        );
      }}
    </ReactHoverObserver>
  );
};
//parameters
const AttributeLabel = ({ labelItem, deleteItem, projectType }) => {
  const canEdit = useCanEdit();
  const [openTooltip, setOpenTooltip] = useState(false);
  const [isHover, setIsHover] = React.useState([false, labelItem?.name]);
  function truncate(str, n) {
    return str.length > n ? str.substr(0, n - 1) + "..." : str;
  }
  function handleToolTipOpen() {
    if (
      isHover[0] &&
      isHover[1] == labelItem?.name &&
      labelItem?.name.length > truncateLength
    ) {
      setOpenTooltip(true);
    } else {
      setOpenTooltip(false);
    }
  }
  return (
    <ReactHoverObserver>
      {({ isHovering }) => {
        return (
          <div className='flex flex-row p-1 h-8 justify-between items-center border-b-2 ml-6 hover:bg-neutral-gray8'>
            <div className='flex flex-row items-center justify-start flex-1'>
              {projectType === "db" && (
                <div className=' w-full grid grid-cols-5 gap-2 items-center '>
                  {" "}
                  <div className='flex justify-self-start items-center'>
                    <img
                      src={AttributeIcon}
                      alt='conektto logo'
                      className='bg-white mr-4'
                      style={{ height: "24px", width: "24px" }}
                    />
                    <Tooltip
                      title={labelItem?.name}
                      open={openTooltip}
                      onClose={handleToolTipOpen}
                      onOpen={handleToolTipOpen}
                      placement='left-start'
                    >
                      <p
                        className='text-overline2'
                        onMouseEnter={() => {
                          setIsHover([true, labelItem?.name]);
                        }}
                        onMouseLeave={() => {
                          setIsHover([false, labelItem?.name]);
                        }}
                      >
                        {" "}
                        {truncate(labelItem?.name, truncateLength)}{" "}
                      </p>
                    </Tooltip>
                  </div>
                  <div className='flex justify-self-start'>
                    {/* empty: no scheme attribute */}
                  </div>
                  <div className='ml-1 flex justify-self-start'>
                    <p className='text-overline2'>{labelItem?.type}</p>
                  </div>
                  <div className='flex justify-self-start'>
                    {/* empty: no isarray Checkbox */}
                  </div>
                  <div className='flex ml-3 justify-self-start'>
                    <p className='text-overline2'>
                      <Checkbox
                        checked={labelItem?.required}
                        // checked={true}
                        style={{
                          color: Colors.brand.secondary,
                          padding: "0",
                        }}
                      />
                    </p>
                  </div>
                </div>
              )}
              {projectType === "schema" ||
                (projectType === "both" && (
                  <div className=' w-full grid grid-cols-5 gap-2 items-center'>
                    {" "}
                    <div className='flex justify-self-start items-center'>
                      <img
                        src={AttributeIcon}
                        alt='conektto logo'
                        className='bg-white mr-4'
                        style={{ height: "24px", width: "24px" }}
                      />
                      <Tooltip
                        title={labelItem?.name}
                        open={openTooltip}
                        onClose={handleToolTipOpen}
                        onOpen={handleToolTipOpen}
                        placement='left-start'
                      >
                        <p
                          onMouseEnter={() => {
                            setIsHover([true, labelItem?.name]);
                          }}
                          onMouseLeave={() => {
                            setIsHover([false, labelItem?.name]);
                          }}
                          className='text-overline2'
                        >
                          {truncate(labelItem?.name, truncateLength)}
                        </p>
                      </Tooltip>{" "}
                    </div>
                    <div className='ml-1 flex justify-self-start'>
                      <p className='text-overline2'>{labelItem?.type}</p>
                    </div>
                    <div className='flex justify-self-start'>
                      {/* empty: no isarray Checkbox */}
                    </div>
                    <div className='flex ml-3 justify-self-start'>
                      {/* <p className='text-overline2'>
                        <Checkbox
                          checked={labelItem?.required}
                          // checked={true}
                          style={{
                            color: Colors.brand.secondary,
                            padding: "0",
                          }}
                        />
                      </p> */}
                      {/* isRequired not needed for now */}
                    </div>
                  </div>
                ))}
            </div>

            <div className='w-6'>
              {isHovering && canEdit() && (
                <AppIcon
                  onClick={(ev) => {
                    ev?.preventDefault();
                    ev?.stopPropagation();

                    deleteItem(labelItem);
                  }}
                >
                  <DeleteIcon />
                </AppIcon>
              )}
            </div>
          </div>
        );
      }}
    </ReactHoverObserver>
  );
};
//drag and drop tables
const DatabaseLabel = ({
  tableLabelItem,
  request,
  responseCode,
  deleteItem,
  isArrayChecked,
}) => {
  const [optionsMenuAnchorEl, setOptionsMenuAnchorEl] = useState(false);
  const [isArray, setIsArray] = useState(tableLabelItem.isArray);
  const [openTooltip, setOpenTooltip] = useState(false);
  const [isHover, setIsHover] = React.useState([
    false,
    tableLabelItem?.sourceName,
  ]);
  const [dialog, setDialog] = useState({
    show: false,
    type: null,
    data: null,
  });
  const nameRef = useRef();
  const canEdit = useCanEdit();

  const setOperationDetails = useSetRecoilState(operationAtomWithMiddleware);

  useDoubleClick({
    onSingleClick: (e) => {},
    onDoubleClick: (e) => {
      e?.preventDefault();
      e?.stopPropagation();

      if (canEdit()) {
        showTableNameChangeDialog();
      }
    },
    ref: nameRef,
    latency: 275,
  });

  const showTableNameChangeDialog = () => {
    if (canEdit()) {
      setDialog({
        show: true,
        type: "rename-table",
      });
    }
  };

  const handleOptionsClick = (event) => {
    setOptionsMenuAnchorEl(event?.currentTarget);
  };

  const handleCloseDialog = () => {
    setDialog({
      show: false,
      data: null,
    });
  };
  function truncate(str, n) {
    return str.length > n ? str.substr(0, n - 1) + "..." : str;
  }
  function handleToolTipOpen() {
    if (
      isHover[0] &&
      isHover[1] == tableLabelItem?.sourceName &&
      tableLabelItem?.sourceName.length > truncateLength
    ) {
      setOpenTooltip(true);
    } else {
      setOpenTooltip(false);
    }
  }
  return (
    <ReactHoverObserver>
      {({ isHovering }) => {
        return (
          <>
            <Dialog
              onClose={handleCloseDialog}
              aria-labelledby='dashboard-dialog'
              open={dialog?.show ?? false}
              fullWidth
              PaperProps={{
                style: { borderRadius: 8 },
              }}
              disableBackdropClick
            >
              {dialog?.type === "rename-table" && canEdit() && (
                <ChangeTableName
                  labelItem={tableLabelItem}
                  request={request}
                  responseCode={responseCode}
                  onClose={handleCloseDialog}
                />
              )}
            </Dialog>

            <div className='flex flex-row p-1 justify-between items-center border-b-2 h-8'>
              <div className='flex flex-row items-center justify-start w-full '>
                <div className='w-full grid grid-cols-5 gap-2 items-center '>
                  {" "}
                  <div className='flex justify-self-start items-center'>
                    <img
                      src={TableIcon}
                      alt='conektto logo'
                      className='bg-white mr-4'
                      style={{ height: "24px", width: "24px" }}
                    />
                    {tableLabelItem?.sourceName &&
                    !_.isEmpty(tableLabelItem?.sourceName) ? (
                      <Tooltip
                        title={tableLabelItem?.sourceName}
                        open={openTooltip}
                        onClose={handleToolTipOpen}
                        onOpen={handleToolTipOpen}
                        placement='left-start'
                      >
                        <p
                          id='tableNameTruncate'
                          onMouseEnter={() => {
                            setIsHover([true, tableLabelItem?.sourceName]);
                          }}
                          onMouseLeave={() => {
                            setIsHover([false, tableLabelItem?.sourceName]);
                          }}
                          className='text-overline2'
                        >
                          {truncate(tableLabelItem?.sourceName, truncateLength)}
                        </p>
                      </Tooltip>
                    ) : null}
                  </div>
                  <div className='flex -ml-4 justify-self-start'>
                    {" "}
                    {tableLabelItem?.name &&
                    !_.isEmpty(tableLabelItem?.name) ? (
                      <p
                        className='text-overline2 ml-4 select-none'
                        ref={nameRef}
                      >
                        {tableLabelItem?.name}
                      </p>
                    ) : null}
                  </div>
                  <div> {/* empty datattype */}</div>
                  <div className='flex  ml-1 justify-self-start'>
                    <Checkbox
                      checked={isArray}
                      onClick={(e) => {
                        e.preventDefault();
                        e.stopPropagation();

                        isArrayChecked(tableLabelItem, !isArray, request);
                        setIsArray(!isArray);
                      }}
                      style={{
                        color: Colors.brand.secondary,
                        padding: "0",
                      }}
                    />
                  </div>
                  <div>{/* empty required */}</div>
                </div>
              </div>

              <div className='w-6'>
                {isHovering && canEdit() && (
                  <>
                    <AppIcon
                      onClick={(ev) => {
                        ev?.preventDefault();
                        ev?.stopPropagation();

                        handleOptionsClick(ev);
                      }}
                    >
                      <MoreVertIcon style={{ fontSize: "24px" }} />
                    </AppIcon>

                    <Menu
                      id='table-menu'
                      anchorEl={optionsMenuAnchorEl}
                      keepMounted
                      open={Boolean(optionsMenuAnchorEl)}
                      onClose={() => {
                        setOptionsMenuAnchorEl(null);
                      }}
                      TransitionComponent={Fade}
                      style={{ borderRadius: "1rem", zIndex: "100" }}
                    >
                      <MenuItem
                        onClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                          setOptionsMenuAnchorEl(null);

                          showTableNameChangeDialog();
                        }}
                      >
                        <p className='text-overline2'>Rename</p>
                      </MenuItem>
                      <MenuItem
                        onClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                          setOptionsMenuAnchorEl(null);

                          deleteItem(tableLabelItem);
                        }}
                      >
                        <p className='text-overline2 text-accent-red'>Delete</p>
                      </MenuItem>
                    </Menu>
                  </>
                )}
              </div>
            </div>
          </>
        );
      }}
    </ReactHoverObserver>
  );
};
//attributes && columns within a table
const ColumnLabel = ({
  columnLabelItem,
  request,
  responseCode,
  deleteColumn,
  renameColumn,
  isNameTaken,
}) => {
  let [operationData, setOperationDetails] = useRecoilState(
    operationAtomWithMiddleware
  );
  const [openTooltip, setOpenTooltip] = useState(false);
  const [isHover, setIsHover] = React.useState([
    false,
    columnLabelItem?.sourceNames,
  ]);
  if (
    columnLabelItem.auto == true &&
    request == true &&
    operationData?.operation?.operationType?.toLowerCase() == "post"
  ) {
    deleteColumn(columnLabelItem);
  }

  const [optionsMenuAnchorEl, setOptionsMenuAnchorEl] = useState(false);
  const [dialog, setDialog] = useState({
    show: false,
    type: null,
    data: null,
  });
  const nameRef = useRef();
  const canEdit = useCanEdit();

  useDoubleClick({
    onSingleClick: (e) => {},
    onDoubleClick: (e) => {
      e?.preventDefault();
      e?.stopPropagation();

      if (canEdit()) {
        showColumnNameChangeDialog();
      }
    },
    ref: nameRef,
    latency: 275,
  });

  const showColumnNameChangeDialog = () => {
    if (canEdit()) {
      setDialog({
        show: true,
        type: "rename-column",
      });
    }
  };

  const handleOptionsClick = (event) => {
    setOptionsMenuAnchorEl(event?.currentTarget);
  };

  const handleCloseDialog = () => {
    setDialog({
      show: false,
      data: null,
    });
  };
  function truncate(str, n) {
    return str.length > n ? str.substr(0, n - 1) + "..." : str;
  }
  function handleToolTipOpen() {
    if (
      isHover[0] &&
      isHover[1] == columnLabelItem?.sourceName &&
      columnLabelItem?.sourceName.length > truncateLength
    ) {
      setOpenTooltip(true);
    } else {
      setOpenTooltip(false);
    }
  }
  return (
    <ReactHoverObserver>
      {({ isHovering }) => {
        return (
          <>
            <Dialog
              onClose={handleCloseDialog}
              aria-labelledby='column-dialog'
              open={dialog?.show ?? false}
              fullWidth
              PaperProps={{
                style: { borderRadius: 8 },
              }}
              disableBackdropClick
            >
              {dialog?.type === "rename-column" && canEdit() && (
                <ChangeColumnName
                  labelItem={columnLabelItem}
                  request={request}
                  responseCode={responseCode}
                  renameColumn={(column, value) => {
                    renameColumn(column, value);

                    handleCloseDialog();
                  }}
                  isNameTaken={isNameTaken}
                  onClose={handleCloseDialog}
                />
              )}
            </Dialog>

            <div className=' flex flex-row p-1 h-8 justify-between items-center border-b-2 ml-6 hover:bg-neutral-gray8'>
              <div className='flex flex-row items-center justify-start flex-1'>
                <div className=' w-full grid grid-cols-5 gap-2 items-center '>
                  {" "}
                  <div className='flex justify-self-start items-center '>
                    <img
                      src={ColumnIcon}
                      alt='conektto logo'
                      className='bg-white mr-4'
                      style={{ height: "24px", width: "24px" }}
                    />
                    <Tooltip
                      title={columnLabelItem?.sourceName}
                      open={openTooltip}
                      onClose={handleToolTipOpen}
                      onOpen={handleToolTipOpen}
                      placement='left-start'
                    >
                      <p
                        className='text-overline2'
                        onMouseEnter={() => {
                          setIsHover([true, columnLabelItem?.sourceName]);
                        }}
                        onMouseLeave={() => {
                          setIsHover([false, columnLabelItem?.sourceName]);
                        }}
                      >
                        {truncate(columnLabelItem?.sourceName, truncateLength)}
                      </p>
                    </Tooltip>
                  </div>
                  <div
                    className='flex justify-self-start  cursor-pointer select-none'
                    ref={nameRef}
                  >
                    <p className='text-overline2'>{columnLabelItem?.name}</p>
                  </div>
                  <div className='flex ml-1 justify-self-start'>
                    <p className='text-overline2'>{columnLabelItem?.type}</p>
                  </div>
                  <div className='flex justify-self-start'>
                    {/* empty: no isarray Checkbox */}
                  </div>
                  <div className='flex ml-3 justify-self-start'>
                    <p className='text-overline2'>
                      <Checkbox
                        checked={columnLabelItem?.required}
                        style={{
                          color: Colors.brand.secondary,
                          padding: "0",
                        }}
                      />
                    </p>
                  </div>
                </div>
              </div>

              <div className='w-6'>
                {isHovering && canEdit() && (
                  <>
                    <AppIcon
                      onClick={(ev) => {
                        ev?.preventDefault();
                        ev?.stopPropagation();

                        handleOptionsClick(ev);
                      }}
                    >
                      <MoreVertIcon />
                    </AppIcon>

                    <Menu
                      id='table-menu'
                      anchorEl={optionsMenuAnchorEl}
                      keepMounted
                      open={Boolean(optionsMenuAnchorEl)}
                      onClose={() => {
                        setOptionsMenuAnchorEl(null);
                      }}
                      TransitionComponent={Fade}
                      style={{ borderRadius: "1rem", zIndex: "100" }}
                    >
                      <MenuItem
                        onClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                          setOptionsMenuAnchorEl(null);

                          showColumnNameChangeDialog();
                        }}
                      >
                        <p className='text-overline2'>Rename</p>
                      </MenuItem>
                      <MenuItem
                        onClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                          setOptionsMenuAnchorEl(null);

                          deleteColumn(columnLabelItem);
                        }}
                      >
                        <p className='text-overline2 text-accent-red'>Delete</p>
                      </MenuItem>
                    </Menu>
                  </>
                )}
              </div>
            </div>
          </>
        );
      }}
    </ReactHoverObserver>
  );
};

const StoredProcedureLabel = ({
  storedProcedureLabelItem,
  request,
  responseCode,
  deleteItem,
  isArrayChecked,
}) => {
  const [optionsMenuAnchorEl, setOptionsMenuAnchorEl] = useState(false);
  const [isArray, setIsArray] = useState(storedProcedureLabelItem.isArray);
  const [openTooltip, setOpenTooltip] = useState(false);
  const [isHover, setIsHover] = React.useState([
    false,
    storedProcedureLabelItem?.sourceName,
  ]);
  const [dialog, setDialog] = useState({
    show: false,
    type: null,
    data: null,
  });
  const nameRef = useRef();
  const canEdit = useCanEdit();

  const setOperationDetails = useSetRecoilState(operationAtomWithMiddleware);

  // useDoubleClick({
  //   onSingleClick: (e) => {},
  //   onDoubleClick: (e) => {
  //     e?.preventDefault();
  //     e?.stopPropagation();

  //     if (canEdit()) {
  //       showTableNameChangeDialog();
  //     }
  //   },
  //   ref: nameRef,
  //   latency: 275,
  // });

  const showTableNameChangeDialog = () => {
    if (canEdit()) {
      setDialog({
        show: true,
        type: "rename-table",
      });
    }
  };

  const handleOptionsClick = (event) => {
    setOptionsMenuAnchorEl(event?.currentTarget);
  };

  const handleCloseDialog = () => {
    setDialog({
      show: false,
      data: null,
    });
  };
  function truncate(str, n) {
    return str.length > n ? str.substr(0, n - 1) + "..." : str;
  }
  function handleToolTipOpen() {
    if (
      isHover[0] &&
      isHover[1] == storedProcedureLabelItem?.name &&
      storedProcedureLabelItem?.name.length > truncateLength
    ) {
      setOpenTooltip(true);
    } else {
      setOpenTooltip(false);
    }
  }

  return (
    <ReactHoverObserver>
      {({ isHovering }) => {
        return (
          <>
            <Dialog
              onClose={handleCloseDialog}
              aria-labelledby='dashboard-dialog'
              open={dialog?.show ?? false}
              fullWidth
              PaperProps={{
                style: { borderRadius: 8 },
              }}
              disableBackdropClick
            >
              {dialog?.type === "rename-table" && canEdit() && (
                <ChangeTableName
                  labelItem={storedProcedureLabelItem}
                  request={request}
                  responseCode={responseCode}
                  onClose={handleCloseDialog}
                />
              )}
            </Dialog>

            <div className='flex flex-row p-1 justify-between items-center border-b-2 h-8'>
              <div className='flex flex-row items-center justify-start w-full '>
                <div className='w-full grid grid-cols-5 gap-2 items-center '>
                  {" "}
                  <div className='flex justify-self-start items-center'>
                    <img
                      src={StoredProcedureIcon}
                      alt='conektto logo'
                      className='bg-white mr-4'
                      style={{ height: "24px", width: "24px" }}
                    />
                    {storedProcedureLabelItem?.name &&
                    !_.isEmpty(storedProcedureLabelItem?.name) ? (
                      <Tooltip
                        title={storedProcedureLabelItem?.name}
                        open={openTooltip}
                        onClose={handleToolTipOpen}
                        onOpen={handleToolTipOpen}
                        placement='left-start'
                      >
                        <p
                          id='tableNameTruncate'
                          onMouseEnter={() => {
                            setIsHover([
                              true,
                              storedProcedureLabelItem?.sourceName,
                            ]);
                          }}
                          onMouseLeave={() => {
                            setIsHover([
                              false,
                              storedProcedureLabelItem?.sourceName,
                            ]);
                          }}
                          className='text-overline2'
                        >
                          {truncate(
                            storedProcedureLabelItem?.name,
                            truncateLength
                          )}
                        </p>
                      </Tooltip>
                    ) : null}
                  </div>
                  <div> {/* empty schema/attribute */}</div>
                  <div> {/* empty datattype */}</div>
                  <div> {/* empty Isarray */}</div>
                  <div>{/* empty required */}</div>
                </div>
              </div>

              <div className='w-6'>
                {isHovering && canEdit() && (
                  <>
                    <AppIcon
                      onClick={(ev) => {
                        ev?.preventDefault();
                        ev?.stopPropagation();

                        handleOptionsClick(ev);
                      }}
                    >
                      <MoreVertIcon style={{ fontSize: "24px" }} />
                    </AppIcon>

                    <Menu
                      id='table-menu'
                      anchorEl={optionsMenuAnchorEl}
                      keepMounted
                      open={Boolean(optionsMenuAnchorEl)}
                      onClose={() => {
                        setOptionsMenuAnchorEl(null);
                      }}
                      TransitionComponent={Fade}
                      style={{ borderRadius: "1rem", zIndex: "100" }}
                    >
                      <MenuItem
                        onClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                          setOptionsMenuAnchorEl(null);

                          showTableNameChangeDialog();
                        }}
                      >
                        <p className='text-overline2'>Rename</p>
                      </MenuItem>
                      <MenuItem
                        onClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                          setOptionsMenuAnchorEl(null);

                          deleteItem(storedProcedureLabelItem);
                        }}
                      >
                        <p className='text-overline2 text-accent-red'>Delete</p>
                      </MenuItem>
                    </Menu>
                  </>
                )}
              </div>
            </div>
          </>
        );
      }}
    </ReactHoverObserver>
  );
};

const InputOrOutputLabel = ({
  inputOrOutputLabelItem,
  request,
  responseCode,
  // deleteColumn,
  renameColumn,
  isNameTaken,
}) => {
  let [operationData, setOperationDetails] = useRecoilState(
    operationAtomWithMiddleware
  );
  const [openTooltip, setOpenTooltip] = useState(false);
  const [isHover, setIsHover] = React.useState([
    false,
    inputOrOutputLabelItem?.sourceNames,
  ]);

  const [optionsMenuAnchorEl, setOptionsMenuAnchorEl] = useState(false);
  const [dialog, setDialog] = useState({
    show: false,
    type: null,
    data: null,
  });
  const nameRef = useRef();
  const canEdit = useCanEdit();

  useDoubleClick({
    onSingleClick: (e) => {},
    onDoubleClick: (e) => {
      e?.preventDefault();
      e?.stopPropagation();

      if (canEdit()) {
        showColumnNameChangeDialog();
      }
    },
    ref: nameRef,
    latency: 275,
  });

  const showColumnNameChangeDialog = () => {
    if (canEdit()) {
      setDialog({
        show: true,
        type: "rename-column",
      });
    }
  };

  const handleOptionsClick = (event) => {
    setOptionsMenuAnchorEl(event?.currentTarget);
  };

  const handleCloseDialog = () => {
    setDialog({
      show: false,
      data: null,
    });
  };
  function truncate(str, n) {
    return str.length > n ? str.substr(0, n - 1) + "..." : str;
  }
  function handleToolTipOpen() {
    if (
      isHover[0] &&
      isHover[1] == inputOrOutputLabelItem?.name &&
      inputOrOutputLabelItem?.name.length > truncateLength
    ) {
      setOpenTooltip(true);
    } else {
      setOpenTooltip(false);
    }
  }
  return (
    <ReactHoverObserver>
      {({ isHovering }) => {
        return (
          <>
            {/* <Dialog
              onClose={handleCloseDialog}
              aria-labelledby='column-dialog'
              open={dialog?.show ?? false}
              fullWidth
              PaperProps={{
                style: { borderRadius: 8 },
              }}
              disableBackdropClick
            >
              {dialog?.type === "rename-column" && canEdit() && (
                <ChangeColumnName
                  labelItem={inputOrOutputLabelItem}
                  request={request}
                  responseCode={responseCode}
                  renameColumn={(column, value) => {
                    renameColumn(column, value);

                    handleCloseDialog();
                  }}
                  isNameTaken={isNameTaken}
                  onClose={handleCloseDialog}
                />
              )}
            </Dialog> */}

            <div className=' flex flex-row p-1 h-8 justify-between items-center border-b-2 ml-6 hover:bg-neutral-gray8'>
              <div className='flex flex-row items-center justify-start flex-1'>
                <div className=' w-full grid grid-cols-5 gap-2 items-center '>
                  {" "}
                  <div className='flex justify-self-start items-center '>
                    <img
                      src={
                        inputOrOutputLabelItem.type == "input"
                          ? InputIcon
                          : inputOrOutputLabelItem.type == "output"
                          ? OutputIcon
                          : null
                      }
                      alt='conektto logo'
                      className='bg-white mr-4'
                      style={{ height: "24px", width: "24px" }}
                    />
                    <Tooltip
                      title={inputOrOutputLabelItem?.name}
                      open={openTooltip}
                      onClose={handleToolTipOpen}
                      onOpen={handleToolTipOpen}
                      placement='left-start'
                    >
                      <p
                        className='text-overline2'
                        onMouseEnter={() => {
                          setIsHover([true, inputOrOutputLabelItem?.name]);
                        }}
                        onMouseLeave={() => {
                          setIsHover([false, inputOrOutputLabelItem?.name]);
                        }}
                      >
                        {truncate(inputOrOutputLabelItem?.name, truncateLength)}
                      </p>
                    </Tooltip>
                  </div>
                  <div
                    className='flex justify-self-start  cursor-pointer select-none'
                    ref={nameRef}
                  >
                    {/* <p className='text-overline2'>
                      {inputOrOutputLabelItem?.name}
                    </p> */}
                  </div>
                  <div className='flex ml-1 justify-self-start'>
                    <p className='text-overline2'>
                      {/* {inputOrOutputLabelItem?.type} */}
                    </p>
                  </div>
                  <div className='flex justify-self-start'>
                    {/* empty: no isarray Checkbox */}
                  </div>
                  <div className='flex ml-3 justify-self-start'>
                    {/* empty: no isarray Checkbox */}
                  </div>
                </div>
              </div>

              {/* <div className='w-6'>
                {isHovering && canEdit() && (
                  <>
                    <AppIcon
                      onClick={(ev) => {
                        ev?.preventDefault();
                        ev?.stopPropagation();

                        handleOptionsClick(ev);
                      }}
                    >
                      <MoreVertIcon />
                    </AppIcon>

                    <Menu
                      id='table-menu'
                      anchorEl={optionsMenuAnchorEl}
                      keepMounted
                      open={Boolean(optionsMenuAnchorEl)}
                      onClose={() => {
                        setOptionsMenuAnchorEl(null);
                      }}
                      TransitionComponent={Fade}
                      style={{ borderRadius: "1rem", zIndex: "100" }}
                    >
                      <MenuItem
                        onClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                          setOptionsMenuAnchorEl(null);

                          showColumnNameChangeDialog();
                        }}
                      >
                        <p className='text-overline2'>Rename</p>
                      </MenuItem>
                      <MenuItem
                        onClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                          setOptionsMenuAnchorEl(null);

                          deleteColumn(inputOrOutputLabelItem);
                        }}
                      >
                        <p className='text-overline2 text-accent-red'>Delete</p>
                      </MenuItem>
                    </Menu>
                  </>
                )}
              </div> */}
            </div>
          </>
        );
      }}
    </ReactHoverObserver>
  );
};

export default Body;
